# [GPX-DOC-v1] Configuracion del analisis estatico de SonarQube, ejecutado por miworkflow.yml en cada push a main.
# Unique identifier for your project in SonarQube
sonar.projectKey=GPX.Web

# Name displayed in the SonarQube UI
sonar.projectName=GPX.Web

# Comma-separated paths to directories containing source code
sonar.sources=GPX.Web,GPX.Negocio
