# Unique identifier for your project in SonarQube
sonar.projectKey=GPX.Web

# Name displayed in the SonarQube UI
sonar.projectName=GPX.Web

# Comma-separated paths to directories containing source code
sonar.sources=GPX.Web,GPX.Negocio
