apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpbaceria-app
  labels:
    app: gpbaceria
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gpbaceria
  template:
    metadata:
      labels:
        app: gpbaceria
    spec:
      containers:
      - name: web-server
        image: 295934382080.dkr.ecr.us-east-1.amazonaws.com/gpbaceria:a8974b9c5e0317ff0f5173c5e567ef9b0c06cf1b
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: gpbaceria-service
spec:
  type: LoadBalancer
  selector:
    app: gpbaceria
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
